//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwithTDD.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class compact_discs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public compact_discs()
        {
            this.tracks1 = new HashSet<track>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string artist { get; set; }
        public Nullable<int> tracks { get; set; }
        public Nullable<decimal> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<track> tracks1 { get; set; }
    }
}
