//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwithTDD.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class track
    {
        public int id { get; set; }
        public int cd_id { get; set; }
        public string title { get; set; }
    
        public virtual compact_discs compact_discs { get; set; }
    }
}
